// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// psbcSpeedUp_internal
Rcpp::List psbcSpeedUp_internal(const std::string& dataFile, const int p, const int q, const std::string& hyperParFile, const std::string& outFilePath, const arma::vec ini_beta, const arma::vec ini_tauSq, const arma::vec ini_h, const arma::uvec groupInd, unsigned int nIter, unsigned int nChains, unsigned int thin, bool rw);
RcppExport SEXP _psbcSpeedUp_psbcSpeedUp_internal(SEXP dataFileSEXP, SEXP pSEXP, SEXP qSEXP, SEXP hyperParFileSEXP, SEXP outFilePathSEXP, SEXP ini_betaSEXP, SEXP ini_tauSqSEXP, SEXP ini_hSEXP, SEXP groupIndSEXP, SEXP nIterSEXP, SEXP nChainsSEXP, SEXP thinSEXP, SEXP rwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type dataFile(dataFileSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type hyperParFile(hyperParFileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type outFilePath(outFilePathSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type ini_beta(ini_betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type ini_tauSq(ini_tauSqSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type ini_h(ini_hSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type groupInd(groupIndSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nChains(nChainsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< bool >::type rw(rwSEXP);
    rcpp_result_gen = Rcpp::wrap(psbcSpeedUp_internal(dataFile, p, q, hyperParFile, outFilePath, ini_beta, ini_tauSq, ini_h, groupInd, nIter, nChains, thin, rw));
    return rcpp_result_gen;
END_RCPP
}
