// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// drive
Rcpp::List drive(const arma::vec& datTime, const arma::uvec& datEvent, const arma::mat& x, const unsigned int p, const unsigned int q, Rcpp::List& hyperParFile, arma::vec beta, arma::vec tauSq, arma::vec h, const arma::uvec groupInd, const unsigned int nIter, const unsigned int nChains, const unsigned int thin, bool rw);
RcppExport SEXP _psbcSpeedUp_drive(SEXP datTimeSEXP, SEXP datEventSEXP, SEXP xSEXP, SEXP pSEXP, SEXP qSEXP, SEXP hyperParFileSEXP, SEXP betaSEXP, SEXP tauSqSEXP, SEXP hSEXP, SEXP groupIndSEXP, SEXP nIterSEXP, SEXP nChainsSEXP, SEXP thinSEXP, SEXP rwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type datTime(datTimeSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type datEvent(datEventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type q(qSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type hyperParFile(hyperParFileSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tauSq(tauSqSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type groupInd(groupIndSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nChains(nChainsSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< bool >::type rw(rwSEXP);
    rcpp_result_gen = Rcpp::wrap(drive(datTime, datEvent, x, p, q, hyperParFile, beta, tauSq, h, groupInd, nIter, nChains, thin, rw));
    return rcpp_result_gen;
END_RCPP
}
