# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drive <- function(datTime, datEvent, x, p, q, hyperParFile, beta, tauSq, h, groupInd, nIter, nChains, thin, rw) {
    .Call(`_psbcSpeedUp_drive`, datTime, datEvent, x, p, q, hyperParFile, beta, tauSq, h, groupInd, nIter, nChains, thin, rw)
}

