# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psbcSpeedUp_internal <- function(datTime, datEvent, x, p, q, hyperParFile, ini_beta, ini_tauSq, ini_h, groupInd, nIter, nChains, thin, rw) {
    .Call('_psbcSpeedUp_psbcSpeedUp_internal', PACKAGE = 'psbcSpeedUp', datTime, datEvent, x, p, q, hyperParFile, ini_beta, ini_tauSq, ini_h, groupInd, nIter, nChains, thin, rw)
}

